//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.07 at 01:43:26 PM EDT 
//

package com.staples.asgard.core.domain.model.inventory;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * <p>
 * Java class for getMultiOnHandRes complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getMultiOnHandRes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="multiOnHandResHdr" type="{http://is.mvs.staples.com/}getMultiOnHandResHdrType"/>
 *         &lt;element name="itemDetails" type="{http://is.mvs.staples.com/}getAllitemsDetailResType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType (XmlAccessType.FIELD)
@XmlType (name = "getMultiOnHandRes", propOrder = { "multiOnHandResHdr", "itemDetails" })
@XmlRootElement (name = "getMultiOnHandRes")
@JsonAutoDetect (getterVisibility = Visibility.PROTECTED_AND_PUBLIC,
				setterVisibility = Visibility.PROTECTED_AND_PUBLIC, fieldVisibility = Visibility.PROTECTED_AND_PUBLIC)
@JsonInclude (Include.NON_NULL)
public class GetMultiOnHandRes implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4856385647835631L;

	@XmlElement(required = true)
    protected GetMultiOnHandResHdrType multiOnHandResHdr;
    protected GetAllitemsDetailResType itemDetails;

    /**
     * Gets the value of the multiOnHandResHdr property.
     * 
     * @return
     *     possible object is
     *     {@link GetMultiOnHandResHdrType }
     *     
     */
    public GetMultiOnHandResHdrType getMultiOnHandResHdr() {
        return multiOnHandResHdr;
    }

    /**
     * Sets the value of the multiOnHandResHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetMultiOnHandResHdrType }
     *     
     */
    public void setMultiOnHandResHdr(GetMultiOnHandResHdrType value) {
        this.multiOnHandResHdr = value;
    }

    /**
     * Gets the value of the itemDetails property.
     * 
     * @return
     *     possible object is
     *     {@link GetAllitemsDetailResType }
     *     
     */
    public GetAllitemsDetailResType getItemDetails() {
        return itemDetails;
    }

    /**
     * Sets the value of the itemDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetAllitemsDetailResType }
     *     
     */
    public void setItemDetails(GetAllitemsDetailResType value) {
        this.itemDetails = value;
    }
}