//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.07 at 01:43:26 PM EDT 
//


package com.staples.asgard.core.domain.model.inventory;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getOnHandRes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getOnHandRes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="statusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="histSeqNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="storeNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="storeZipCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="storeLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="itemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="itemDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="itemStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="itemImageURI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="alocQty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="availQty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="damageQty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="displayQty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="onHandQty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="softAllocQty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="inTransitQty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pendingQty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="invLastUptDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="invLastUptTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inTransitDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="velocity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="stockLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getOnHandRes", propOrder = {
    "status",
    "statusDesc",
    "histSeqNum",
    "storeNum",
    "storeZipCode",
    "storeLocation",
    "itemId",
    "itemDesc",
    "itemStatus",
    "itemImageURI",
    "alocQty",
    "availQty",
    "damageQty",
    "displayQty",
    "onHandQty",
    "softAllocQty",
    "inTransitQty",
    "pendingQty",
    "invLastUptDate",
    "invLastUptTime",
    "inTransitDate",
    "velocity",
    "stockLevel"
})
public class GetOnHandRes {

    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String statusDesc;
    @XmlElement(required = true)
    protected String histSeqNum;
    @XmlElement(required = true)
    protected String storeNum;
    protected String storeZipCode;
    protected String storeLocation;
    @XmlElement(required = true)
    protected String itemId;
    protected String itemDesc;
    protected String itemStatus;
    protected String itemImageURI;
    @XmlElement(required = true)
    protected String alocQty;
    @XmlElement(required = true)
    protected String availQty;
    @XmlElement(required = true)
    protected String damageQty;
    @XmlElement(required = true)
    protected String displayQty;
    @XmlElement(required = true)
    protected String onHandQty;
    @XmlElement(required = true)
    protected String softAllocQty;
    @XmlElement(required = true)
    protected String inTransitQty;
    @XmlElement(required = true)
    protected String pendingQty;
    protected String invLastUptDate;
    protected String invLastUptTime;
    protected String inTransitDate;
    protected String velocity;
    @XmlElement(required = true)
    protected String stockLevel;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the statusDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusDesc() {
        return statusDesc;
    }

    /**
     * Sets the value of the statusDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusDesc(String value) {
        this.statusDesc = value;
    }

    /**
     * Gets the value of the histSeqNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHistSeqNum() {
        return histSeqNum;
    }

    /**
     * Sets the value of the histSeqNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHistSeqNum(String value) {
        this.histSeqNum = value;
    }

    /**
     * Gets the value of the storeNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoreNum() {
        return storeNum;
    }

    /**
     * Sets the value of the storeNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoreNum(String value) {
        this.storeNum = value;
    }

    /**
     * Gets the value of the storeZipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoreZipCode() {
        return storeZipCode;
    }

    /**
     * Sets the value of the storeZipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoreZipCode(String value) {
        this.storeZipCode = value;
    }

    /**
     * Gets the value of the storeLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoreLocation() {
        return storeLocation;
    }

    /**
     * Sets the value of the storeLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoreLocation(String value) {
        this.storeLocation = value;
    }

    /**
     * Gets the value of the itemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * Sets the value of the itemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemId(String value) {
        this.itemId = value;
    }

    /**
     * Gets the value of the itemDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemDesc() {
        return itemDesc;
    }

    /**
     * Sets the value of the itemDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemDesc(String value) {
        this.itemDesc = value;
    }

    /**
     * Gets the value of the itemStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemStatus() {
        return itemStatus;
    }

    /**
     * Sets the value of the itemStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemStatus(String value) {
        this.itemStatus = value;
    }

    /**
     * Gets the value of the itemImageURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemImageURI() {
        return itemImageURI;
    }

    /**
     * Sets the value of the itemImageURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemImageURI(String value) {
        this.itemImageURI = value;
    }

    /**
     * Gets the value of the alocQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlocQty() {
        return alocQty;
    }

    /**
     * Sets the value of the alocQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlocQty(String value) {
        this.alocQty = value;
    }

    /**
     * Gets the value of the availQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailQty() {
        return availQty;
    }

    /**
     * Sets the value of the availQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailQty(String value) {
        this.availQty = value;
    }

    /**
     * Gets the value of the damageQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDamageQty() {
        return damageQty;
    }

    /**
     * Sets the value of the damageQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDamageQty(String value) {
        this.damageQty = value;
    }

    /**
     * Gets the value of the displayQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayQty() {
        return displayQty;
    }

    /**
     * Sets the value of the displayQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayQty(String value) {
        this.displayQty = value;
    }

    /**
     * Gets the value of the onHandQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnHandQty() {
        return onHandQty;
    }

    /**
     * Sets the value of the onHandQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnHandQty(String value) {
        this.onHandQty = value;
    }

    /**
     * Gets the value of the softAllocQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftAllocQty() {
        return softAllocQty;
    }

    /**
     * Sets the value of the softAllocQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftAllocQty(String value) {
        this.softAllocQty = value;
    }

    /**
     * Gets the value of the inTransitQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInTransitQty() {
        return inTransitQty;
    }

    /**
     * Sets the value of the inTransitQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInTransitQty(String value) {
        this.inTransitQty = value;
    }

    /**
     * Gets the value of the pendingQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPendingQty() {
        return pendingQty;
    }

    /**
     * Sets the value of the pendingQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPendingQty(String value) {
        this.pendingQty = value;
    }

    /**
     * Gets the value of the invLastUptDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvLastUptDate() {
        return invLastUptDate;
    }

    /**
     * Sets the value of the invLastUptDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvLastUptDate(String value) {
        this.invLastUptDate = value;
    }

    /**
     * Gets the value of the invLastUptTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvLastUptTime() {
        return invLastUptTime;
    }

    /**
     * Sets the value of the invLastUptTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvLastUptTime(String value) {
        this.invLastUptTime = value;
    }

    /**
     * Gets the value of the inTransitDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInTransitDate() {
        return inTransitDate;
    }

    /**
     * Sets the value of the inTransitDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInTransitDate(String value) {
        this.inTransitDate = value;
    }

    /**
     * Gets the value of the velocity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVelocity() {
        return velocity;
    }

    /**
     * Sets the value of the velocity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVelocity(String value) {
        this.velocity = value;
    }

    /**
     * Gets the value of the stockLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStockLevel() {
        return stockLevel;
    }

    /**
     * Sets the value of the stockLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStockLevel(String value) {
        this.stockLevel = value;
    }

}
