/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.staples.asgard.core.domain.model.price;


public class OfferElement {
	private java.lang.String tradeposcn_id;

	public void setTradeposcn_id(java.lang.String tradeposcn_id) {
		this.tradeposcn_id = tradeposcn_id;
	}

	public java.lang.String getTradeposcn_id() {
		return tradeposcn_id;
	}

	private java.lang.String qtylimit;

	public void setQtylimit(java.lang.String qtylimit) {
		this.qtylimit = qtylimit;
	}

	public java.lang.String getQtylimit() {
		return qtylimit;
	}

	private java.lang.String compareprice;

	public void setCompareprice(java.lang.String compareprice) {
		this.compareprice = compareprice;
	}

	public java.lang.String getCompareprice() {
		return compareprice;
	}

	private java.lang.String maxqty;

	public void setMaxqty(java.lang.String maxqty) {
		this.maxqty = maxqty;
	}

	public java.lang.String getMaxqty() {
		return maxqty;
	}

	private java.lang.String minimumqty;

	public void setMinimumqty(java.lang.String minimumqty) {
		this.minimumqty = minimumqty;
	}

	public java.lang.String getMinimumqty() {
		return minimumqty;
	}

	private java.lang.Integer offer_id;

	public void setOffer_id(java.lang.Integer offer_id) {
		this.offer_id = offer_id;
	}

	public java.lang.Integer getOffer_id() {
		return offer_id;
	}

	private String price;

	public void setPrice(String price) {
		this.price = price;
	}

	public String getPrice() {
		return price;
	}

}