/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.staples.asgard.core.domain.model.price;

public class PromotionElement {
	private java.lang.String freeshipping;

	public void setFreeshipping(java.lang.String freeshipping) {
		this.freeshipping = freeshipping;
	}

	public java.lang.String getFreeshipping() {
		return freeshipping;
	}

	private PromomessageElement[] promomessage;

	public void setPromomessage(PromomessageElement[] promomessage) {
		this.promomessage = promomessage;
	}

	public PromomessageElement[] getPromomessage() {
		return promomessage;
	}

	private Autoaddpromotion autoaddpromotion;

	public Autoaddpromotion getAutoaddpromotion() {
		return autoaddpromotion;
	}

	public void setAutoaddpromotion(Autoaddpromotion autoaddpromotion) {
		this.autoaddpromotion = autoaddpromotion;
	}

}