/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.staples.asgard.core.domain.model.price;

public class PromomessageElement {

	public PromomessageElement(Integer typeid) {
		super();
		this.typeid = typeid;
	}

	public PromomessageElement() {
	}

	private java.lang.String enddate;

	public void setEnddate(java.lang.String enddate) {
		this.enddate = enddate;
	}

	public java.lang.String getEnddate() {
		return enddate;
	}

	private java.lang.String startdate;

	public void setStartdate(java.lang.String startdate) {
		this.startdate = startdate;
	}

	public java.lang.String getStartdate() {
		return startdate;
	}

	private java.lang.String text;

	public void setText(java.lang.String text) {
		this.text = text;
	}

	public java.lang.String getText() {
		return text;
	}

	private java.lang.Integer typeid;

	public void setTypeid(java.lang.Integer typeid) {
		this.typeid = typeid;
	}

	public java.lang.Integer getTypeid() {
		return typeid;
	}

	private java.lang.String name;

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

	private java.lang.String promoValue;

	public void setPromoValue(java.lang.String promoValue) {
		this.promoValue = promoValue;
	}

	public java.lang.String getPromoValue() {
		return promoValue;
	}

	private java.lang.String promoType;

	public void setPromoType(java.lang.String promoType) {
		this.promoType = promoType;
	}

	public java.lang.String getPromoType() {
		return promoType;
	}

	public boolean equals(PromomessageElement promotion) {
		boolean result;
		if ((promotion == null) || (getClass() != promotion.getClass())) {
			result = false;
		} // end if
		else {
			result = typeid.equals(promotion.typeid);
		} // end else

		return result;
	}

}