/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.staples.asgard.core.domain.model.price;

public class RebatElement {
	private java.lang.String value;

	public void setValue(java.lang.String value) {
		this.value = value;
	}

	public java.lang.String getValue() {
		return value;
	}

	private java.lang.Integer type;

	public void setType(java.lang.Integer type) {
		this.type = type;
	}

	public java.lang.Integer getType() {
		return type;
	}

	private java.lang.String document;

	public void setDocument(java.lang.String document) {
		this.document = document;
	}

	public java.lang.String getDocument() {
		return document;
	}

	private java.lang.Integer complex;

	public void setComplex(java.lang.Integer complex) {
		this.complex = complex;
	}

	public java.lang.Integer getComplex() {
		return complex;
	}

	private java.lang.String rebate_id;

	public void setRebate_id(java.lang.String rebate_id) {
		this.rebate_id = rebate_id;
	}

	public java.lang.String getRebate_id() {
		return rebate_id;
	}

}