/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.staples.asgard.core.domain.model.price;

public class ValueElement {
	private OfferElement[] offer;

	public void setOffer(OfferElement[] offer) {
		this.offer = offer;
	}

	public OfferElement[] getOffer() {
		return offer;
	}

	private java.lang.String zone_id;

	public java.lang.String getZone_id() {
		return zone_id;
	}

	public void setZone_id(java.lang.String zone_id) {
		this.zone_id = zone_id;
	}

	private java.lang.String zone_name;

	public void setZone_name(java.lang.String zone_name) {
		this.zone_name = zone_name;
	}

	public java.lang.String getZone_name() {
		return zone_name;
	}

	private java.lang.Integer precedence;

	public void setPrecedence(java.lang.Integer precedence) {
		this.precedence = precedence;
	}

	public java.lang.Integer getPrecedence() {
		return precedence;
	}

}