/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.staples.asgard.core.domain.model;

import com.staples.asgard.core.domain.model.price.PromotionElement;
import com.staples.asgard.core.domain.model.price.RebatElement;
import com.staples.asgard.core.domain.model.price.ValueElement;

public class PriceOutputVO {
	/*
	 * private Price price;
	 * 
	 * public void setPrice(Price price) { this.price = price; }
	 * 
	 * public Price getPrice() { return price; }
	 */

	private java.lang.Integer user_price_flag;

	public void setUser_price_flag(java.lang.Integer user_price_flag) {
		this.user_price_flag = user_price_flag;
	}

	public java.lang.Integer getUser_price_flag() {
		return user_price_flag;
	}

	private java.lang.String currency;

	public void setCurrency(java.lang.String currency) {
		this.currency = currency;
	}

	public java.lang.String getCurrency() {
		return currency;
	}

	private RebatElement[] rebates;

	public void setRebates(RebatElement[] rebates) {
		this.rebates = rebates;
	}

	public RebatElement[] getRebates() {
		return rebates;
	}

	private PromotionElement promotions;

	public void setPromotions(PromotionElement promotions) {
		this.promotions = promotions;
	}

	public PromotionElement getPromotions() {
		return promotions;
	}

	private ValueElement[] values;

	public void setValues(ValueElement[] values) {
		this.values = values;
	}

	public ValueElement[] getValues() {
		return values;
	}

	private java.lang.String uom;

	public void setUom(java.lang.String uom) {
		this.uom = uom;
	}

	public java.lang.String getUom() {
		return uom;
	}

	public String getDocKey() {
		return docKey;
	}

	public void setDocKey(String docKey) {
		this.docKey = docKey;
	}

	private String docKey = null;

}